In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("archive/Weather Test Data.csv")
df.head()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes

In [4]:
df.columns

Index(['row ID', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row ID         42677 non-null  str
 1   Location       42677 non-null  str
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  str
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  str
 10  WindDir3pm     41547 non-null  str
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3pm       25585 non-null  float64
 19  Temp9am        42387 non-null  float64
 20  Temp3pm        41855 non-null  float64
 21  RainToday      42250 non-null  str
dtypes: float64(16), str(6)
memory usage: 7.2 MB

In [6]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,42483.000000,42585.000000,42250.000000,24365.000000,22178.000000,39887.000000,42264.000000,41882.000000,42136.000000,41573.000000,38411.000000,38432.000000,26592.000000,25585.000000,42387.000000,41855.000000
mean,12.210032,23.246068,2.342862,5.489715,7.647831,40.001379,13.995315,18.607516,68.791176,51.597672,1017.581591,1015.192792,4.412041,4.466054,17.028266,21.700982
std,6.432122,7.123596,8.412106,4.248850,3.778019,13.605915,8.872445,8.806916,18.996115,20.844525,7.094070,7.016408,2.887927,2.729640,6.501771,6.951426
min,-8.200000,-4.800000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.000000,1.000000,982.200000,977.100000,0.000000,0.000000,-7.200000,-5.400000
25%,7.600000,18.000000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.800000,21.100000
75%,16.900000,28.300000,0.600000,7.400000,10.700000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.500000
max,31.800000,47.000000,278.400000,145.000000,14.300000,122.000000,74.000000,83.000000,100.000000,100.000000,1040.400000,1038.900000,8.000000,8.000000,39.400000,45.400000

In [9]:
df.corr(numeric_only=True)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
MinTemp,1.000000,0.734864,0.103974,0.454217,0.067794,0.173617,0.171128,0.179539,-0.227895,0.009694,-0.447121,-0.457477,0.088455,0.026645,0.901141,0.707059
MaxTemp,0.734864,1.000000,-0.076083,0.573770,0.471313,0.059238,0.006747,0.050722,-0.501485,-0.508003,-0.325413,-0.421588,-0.285842,-0.280705,0.886941,0.984513
Rainfall,0.103974,-0.076083,1.000000,-0.059878,-0.230401,0.130114,0.083846,0.049519,0.228248,0.256338,-0.170362,-0.129270,0.203896,0.180069,0.010754,-0.078503
Evaporation,0.454217,0.573770,-0.059878,1.000000,0.365834,0.196842,0.189103,0.131762,-0.500517,-0.388512,-0.256875,-0.279453,-0.174129,-0.187036,0.533074,0.560454
Sunshine,0.067794,0.471313,-0.230401,0.365834,1.000000,-0.044084,-0.000679,0.056008,-0.496319,-0.632841,0.048961,-0.016969,-0.679571,-0.708189,0.290939,0.492496
WindGustSpeed,0.173617,0.059238,0.130114,0.196842,-0.044084,1.000000,0.602298,0.685141,-0.207109,-0.022317,-0.454939,-0.408747,0.077382,0.113722,0.143219,0.026201
WindSpeed9am,0.171128,0.006747,0.083846,0.189103,-0.000679,0.602298,1.000000,0.523991,-0.262888,-0.030996,-0.224376,-0.170661,0.027122,0.053893,0.122488,-0.001017
WindSpeed3pm,0.179539,0.050722,0.049519,0.131762,0.056008,0.685141,0.523991,1.000000,-0.145578,0.016735,-0.294955,-0.254904,0.047801,0.021153,0.165608,0.029677
Humidity9am,-0.227895,-0.501485,0.228248,-0.500517,-0.496319,-0.207109,-0.262888,-0.145578,1.000000,0.670512,0.132162,0.180128,0.459730,0.369118,-0.467416,-0.496403
Humidity3pm,0.009694,-0.508003,0.256338,-0.388512,-0.632841,-0.022317,-0.030996,0.016735,0.670512,1.000000,-0.034798,0.046447,0.524394,0.530554,-0.219518,-0.557057
Pressure9am,-0.447121,-0.325413,-0.170362,-0.256875,0.048961,-0.454939,-0.224376,-0.294955,0.132162,-0.034798,1.000000,0.961074,-0.137782,-0.159840,-0.417100,-0.280220
Pressure3pm,-0.457477,-0.421588,-0.129270,-0.279453,-0.016969,-0.408747,-0.170661,-0.254904,0.180128,0.046447,0.961074,1.000000,-0.067852,-0.094387,-0.465084,-0.384134
Cloud9am,0.088455,-0.285842,0.203896,-0.174129,-0.679571,0.077382,0.027122,0.047801,0.459730,0.524394,-0.137782,-0.067852,1.000000,0.604871,-0.132341,-0.299561
Cloud3pm,0.026645,-0.280705,0.180069,-0.187036,-0.708189,0.113722,0.053893,0.021153,0.369118,0.530554,-0.159840,-0.094387,0.604871,1.000000,-0.127731,-0.319487
Temp9am,0.901141,0.886941,0.010754,0.533074,0.290939,0.143219,0.122488,0.165608,-0.467416,-0.219518,-0.417100,-0.465084,-0.132341,-0.127731,1.000000,0.860869
Temp3pm,0.707059,0.984513,-0.078503,0.560454,0.492496,0.026201,-0.001017,0.029677,-0.496403,-0.557057,-0.280220,-0.384134,-0.299561,-0.319487,0.860869,1.000000